from pygame import USEREVENT
SETVISIBLEMOUSE = USEREVENT + 1
RESUME = USEREVENT + 2
EXITINMENU = USEREVENT + 3
SAVEGAME = USEREVENT + 4
SETSIZESCREEN = USEREVENT + 5
LOADLASTSAVE = USEREVENT + 6
SETVOLUME = USEREVENT + 7
TOGGLEFULLSCREEN = USEREVENT + 8
SAVESETTINGS = USEREVENT + 9
LOADSETTINGS = USEREVENT + 10
